[package]
name = "gfx-hal-tutorials"
version = "0.1.0"
authors = ["Claire Harris <wishing.engine@gmail.com>"]

[dependencies]
winit = "=0.15.1"

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
rev = "3d7d45c3"

[dependencies.gfx-backend-metal]
git = "https://github.com/gfx-rs/gfx"
rev = "3d7d45c3"

[build-dependencies]
glsl-to-spirv = "=0.1.5"
