[package]
name = "gfx-hal-tutorials"
version = "0.1.0"
authors = ["Claire Harris <wishing.engine@gmail.com>"]

[dependencies]
image = "~0.19.0"
winit = "=0.17.2"

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
rev = "16feb392"

[dependencies.gfx-backend-metal]
git = "https://github.com/gfx-rs/gfx"
rev = "16feb392"

[build-dependencies]
glsl-to-spirv = "=0.1.6"
